export {
  Resource,
  PropertiesBase,
  PropertyValues,
  ResolvedPropertyValues as ResolvedInputs,
  OutputValues,
  ResourceGroup,
} from './resource';
export {
  GenerationResult,
  PropertyDefinition,
  dependentGenerator,
  generator,
  getLink,
  def,
  constrain,
  bool,
  str,
  int,
  float,
  date,
  undefinable,
  nullOrUndefinable,
  nullable,
  array,
  complex,
  lookup,
  mapValue,
  mapValues,
} from './properties/properties';
export { DesiredState, createDesiredState } from './desired-state';
