export const ERROR_CATEGORIES = {
  NAMES: {
    INVALID_RESOURCE_NAME: 'INVALID_RESOURCE_NAME',
    DUPLICATE_RESOURCE_NAME: 'DUPLICATE_RESOURCE_NAME',
  },
  DEPENDENCIES: {
    DELETED_RESOURCE_DEPENDENCY: 'DELETED_RESOURCE_DEPENDENCY'
  }
};
