name: Publish Package to GitHub
on:
  push:
    branches:
      - "main"
  # release:
  #   types: [published]
jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@haydenon"
      - run: yarn
      - run: yarn workspace @haydenon/gen-core build
      - run: yarn workspace @haydenon/gen-core npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}