name: Publish Package to GitHub
on:
  release:
    types: [published]
jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@haydenon"
      - run: yarn
        working-directory: ./packages/core
      - run: yarn build
        working-directory: ./packages/core
      - run: yarn npm publish
        working-directory: ./packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
